var MIN_UPGRADERS;
var MIN_BUILDERS;
var MIN_HARVESTERS;
var MIN_NOMAD_HARVESTERS;

function initDefines(){
    MIN_UPGRADERS = 2;
    MIN_BUILDERS = 3;
    MIN_HARVESTERS = 7;
    MIN_NOMAD_HARVESTERS = 5;
}